spring:
  application:
    name: CapstoneOne

resilience4j:
  ratelimiter:
    instances:
      loginRateLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0s

  circuitbreaker:
    instances:
      externalLoginService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2